=== Josst343/XML1/Semana2/Contacts.dtd
<!ELEMENT contacts (contact*)>
<!ATTLIST contacts version CDATA #FIXED "1.0">
<!ATTLIST contacts source CDATA #IMPLIED>
<!ELEMENT contact (name, location, phone, knows, description)>
<!ATTLIST contact alias CDATA #IMPLIED>
<!ELEMENT name (first+, middle?, last)>
<!ELEMENT first (#PCDATA)>
<!ELEMENT middle (#PCDATA)>
<!ELEMENT last (#PCDATA)>
<!ELEMENT location (address | (latitude, longitude))*>
<!ELEMENT address (#PCDATA)>
<!ELEMENT latitude (#PCDATA)>
<!ELEMENT longitude (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ATTLIST phone phone-kind (Home | Work | Cell | Fax) "Home">
<!ELEMENT knows EMPTY>
<!ELEMENT description (#PCDATA)>

=== Josst343/XML1/Semana2/Contacts.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE contacts SYSTEM "Contacts.dtd">
<contacts version="1.0" source="">
    <contact alias="">
        <name>
            <first>Josue</first>
            <middle>Misael</middle>
            <last>Flores</last>
        </name>
        <location>
            <address>Berenjena 8 col. El manto alcaldia iztapalapa</address>
        </location>
        <phone phone-kind="Cell">5516039201</phone>
        <knows></knows>
        <description></description>
    </contact>
</contacts>
